server:
  port: 18761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 60
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
            defaultZone: http://localhost:18761/eureka/


